
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: 127.0.0.1
  port: 3307

development:
  <<: *default
  database: satuforce
sdkjcnjskdnckj
test:
  <<: *default
  database: dell_test

production:
  <<: *default
  database: dell_production
  username: root
#  password: <%= ENV['DELL_DATABASE_PASSWORD'] %>
  password: password
